### PR TITLE
Clarify the location where the ruby is missing

### PR DESCRIPTION
**Pull request by creitve**
For the Issue #73

### CODE REVIEW

**Comment by creitve** [comment]
Also tell me if you do need to update the changelog for this

**Comment by mattbrictson** [comment]
Hi, thanks for creating this PR! Yes, I think a CHANGELOG entry is warranted here.

Also, I think the warning could be improved even further by including the host name. The host is passed to every `on` block, so you can do it like this:

```ruby
# Notice the additional `host` argument
on release_roles(fetch(:rbenv_roles)) do |host|
  # ...
  warn "rbenv: #{rbenv_ruby} is not installed or not found in #{fetch(:rbenv_ruby_dir)} on #{host}"
```

**Comment by creitve** [comment]
Еhanks for your help! I hope that this will suffice.

**Comment by mattbrictson** [comment]
Looks good, thanks! 🙇

**Pull request merged**
